-- Lucid v1 additive migration.
-- This mirrors the database changes applied to the connected Leafline Supabase project.
-- It intentionally preserves legacy Leafline tables and introduces the persistent learning OS tables.
-- See the deployed project migration history for the authoritative applied version.

create extension if not exists pgcrypto;

alter table public.profiles add column if not exists coaching_mode text default 'gentle';
alter table public.profiles add column if not exists visibility jsonb not null default '{"level_xp":true,"streak":true,"subject_levels":true,"badges":true,"aggregate_stats":true,"exact_location":false}'::jsonb;
alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.rooms add column if not exists objective text default '';
alter table public.rooms add column if not exists default_mode text default 'parallel';
alter table public.rooms add column if not exists max_members integer not null default 20;
alter table public.rooms add column if not exists focus_minutes integer not null default 45;
alter table public.rooms add column if not exists break_minutes integer not null default 7;
alter table public.rooms add column if not exists challenge_schedule jsonb not null default '{}'::jsonb;

create table if not exists public.lucid_resources (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,type text not null,title text not null,author text,source_url text,mime_type text,local_reference text,metadata jsonb not null default '{}'::jsonb,processing_status text not null default 'ready',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.resource_pages (id uuid primary key default gen_random_uuid(),resource_id uuid not null references public.lucid_resources(id) on delete cascade,page_number integer not null,text_content text,metadata jsonb not null default '{}'::jsonb,unique(resource_id,page_number));
create table if not exists public.resource_sections (id uuid primary key default gen_random_uuid(),resource_id uuid not null references public.lucid_resources(id) on delete cascade,parent_id uuid references public.resource_sections(id) on delete set null,title text not null,order_index integer not null default 0,start_page integer,end_page integer,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.resource_videos (id uuid primary key default gen_random_uuid(),resource_id uuid not null references public.lucid_resources(id) on delete cascade,youtube_video_id text,youtube_playlist_id text,duration_seconds integer,chapters jsonb not null default '[]'::jsonb,transcript text,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.catalogues (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,title text not null,description text,icon text,cover_url text,goal_summary text,deadline timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.catalogue_resources (id uuid primary key default gen_random_uuid(),catalogue_id uuid not null references public.catalogues(id) on delete cascade,resource_id uuid not null references public.lucid_resources(id) on delete cascade,order_index integer not null default 0,status text not null default 'active',created_at timestamptz not null default now(),unique(catalogue_id,resource_id));
create table if not exists public.learning_goals (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,catalogue_id uuid references public.catalogues(id) on delete cascade,title text not null,description text,target_type text not null default 'milestone',target_value numeric,deadline timestamptz,status text not null default 'active',created_at timestamptz not null default now(),completed_at timestamptz);
create table if not exists public.learning_journeys (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,catalogue_id uuid references public.catalogues(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete cascade,position jsonb not null default '{}'::jsonb,completion numeric not null default 0 check(completion between 0 and 100),exposure numeric not null default 0 check(exposure between 0 and 100),understanding numeric not null default 0 check(understanding between 0 and 100),recall numeric not null default 0 check(recall between 0 and 100),application numeric not null default 0 check(application between 0 and 100),next_review_at timestamptz,last_activity_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(owner_id,catalogue_id,resource_id));
create table if not exists public.reading_sessions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete set null,catalogue_id uuid references public.catalogues(id) on delete set null,started_at timestamptz not null default now(),ended_at timestamptz,planned_seconds integer,active_seconds integer not null default 0,pages_started integer not null default 0,pages_completed integer not null default 0,objective text,result jsonb not null default '{}'::jsonb);
create table if not exists public.video_sessions (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete set null,catalogue_id uuid references public.catalogues(id) on delete set null,started_at timestamptz not null default now(),ended_at timestamptz,active_seconds integer not null default 0,last_timestamp_seconds numeric not null default 0,playback_speed numeric not null default 1,completed boolean not null default false,result jsonb not null default '{}'::jsonb);
create table if not exists public.learning_annotations (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,resource_id uuid not null references public.lucid_resources(id) on delete cascade,resource_page_id uuid references public.resource_pages(id) on delete cascade,annotation_type text not null,color text,body text,geometry jsonb not null default '{}'::jsonb,timestamp_seconds numeric,visibility text not null default 'private',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.lucid_highlights (id uuid primary key default gen_random_uuid(),annotation_id uuid not null unique references public.learning_annotations(id) on delete cascade,semantic_type text not null default 'important',quoted_text text not null,created_at timestamptz not null default now());
create table if not exists public.lucid_bookmarks (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,resource_id uuid not null references public.lucid_resources(id) on delete cascade,page_number integer,timestamp_seconds numeric,label text,created_at timestamptz not null default now());
create table if not exists public.quizzes (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete cascade,catalogue_id uuid references public.catalogues(id) on delete cascade,quiz_type text not null,title text,difficulty text,source_context jsonb not null default '{}'::jsonb,skippable boolean not null default true,milestone_required boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.questions (id uuid primary key default gen_random_uuid(),quiz_id uuid not null references public.quizzes(id) on delete cascade,question_type text not null default 'mcq',prompt text not null,options jsonb not null default '[]'::jsonb,answer jsonb,explanation text,difficulty numeric,concept_id uuid,order_index integer not null default 0);
create table if not exists public.quiz_attempts (id uuid primary key default gen_random_uuid(),quiz_id uuid not null references public.quizzes(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,started_at timestamptz not null default now(),completed_at timestamptz,score numeric,max_score numeric,skipped boolean not null default false,result jsonb not null default '{}'::jsonb);
create table if not exists public.quiz_answers (id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.quiz_attempts(id) on delete cascade,question_id uuid not null references public.questions(id) on delete cascade,answer jsonb,is_correct boolean,feedback text,response_time_seconds numeric);
create table if not exists public.concepts (id uuid primary key default gen_random_uuid(),title text not null,normalized_key text not null unique,description text,metadata jsonb not null default '{}'::jsonb);
create table if not exists public.concept_resources (concept_id uuid not null references public.concepts(id) on delete cascade,resource_id uuid not null references public.lucid_resources(id) on delete cascade,evidence jsonb not null default '{}'::jsonb,primary key(concept_id,resource_id));
create table if not exists public.concept_mastery (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,concept_id uuid not null references public.concepts(id) on delete cascade,exposure numeric not null default 0,understanding numeric not null default 0,recall numeric not null default 0,application numeric not null default 0,mastery numeric not null default 0,evidence jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),unique(user_id,concept_id));
create table if not exists public.room_members (id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null default 'learner',status text not null default 'active',current_mode text not null default 'parallel',commitment_minutes integer,joined_at timestamptz not null default now(),unique(room_id,user_id));
create table if not exists public.room_sessions (id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id) on delete cascade,started_by uuid references auth.users(id) on delete set null,mode text not null,started_at timestamptz not null default now(),ended_at timestamptz,objective text,result jsonb not null default '{}'::jsonb);
create table if not exists public.room_events (id bigint generated always as identity primary key,room_id uuid not null references public.rooms(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,event_type text not null,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now());
create table if not exists public.room_discussions (id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id) on delete cascade,started_by uuid references auth.users(id) on delete set null,topic text,duration_seconds integer not null default 600,started_at timestamptz not null default now(),ended_at timestamptz,summary text,ai_wrapup jsonb not null default '{}'::jsonb);
create table if not exists public.room_discussion_messages (id bigint generated always as identity primary key,discussion_id uuid not null references public.room_discussions(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,message_type text not null default 'text',body text,created_at timestamptz not null default now());
create table if not exists public.room_tests (id uuid primary key default gen_random_uuid(),room_id uuid not null references public.rooms(id) on delete cascade,created_by uuid references auth.users(id) on delete set null,title text,generated_from jsonb not null default '{}'::jsonb,quiz_id uuid references public.quizzes(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.room_test_attempts (id uuid primary key default gen_random_uuid(),room_test_id uuid not null references public.room_tests(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,score numeric,max_score numeric,improvement numeric,completed_at timestamptz,result jsonb not null default '{}'::jsonb,unique(room_test_id,user_id));
create table if not exists public.user_xp (user_id uuid primary key references auth.users(id) on delete cascade,xp bigint not null default 0,level integer not null default 1,streak_days integer not null default 0,updated_at timestamptz not null default now());
create table if not exists public.xp_ledger (id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,event_type text not null,amount integer not null,source_id text,created_at timestamptz not null default now());
create table if not exists public.user_levels (user_id uuid not null references auth.users(id) on delete cascade,level integer not null,title text not null,reached_at timestamptz not null default now(),primary key(user_id,level));
create table if not exists public.badges (id uuid primary key default gen_random_uuid(),slug text not null unique,name text not null,family text not null,description text not null,rule jsonb not null default '{}'::jsonb);
create table if not exists public.user_badges (user_id uuid not null references auth.users(id) on delete cascade,badge_id uuid not null references public.badges(id) on delete cascade,awarded_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb,primary key(user_id,badge_id));
create table if not exists public.recommendations (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,catalogue_id uuid references public.catalogues(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete cascade,action_type text not null,reason text not null,priority numeric not null default 0,accepted_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.learning_patterns (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,pattern_key text not null,dimension text not null,evidence jsonb not null default '{}'::jsonb,confidence numeric,detected_at timestamptz not null default now(),active boolean not null default true,unique(user_id,pattern_key));
create table if not exists public.ai_conversations (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,resource_id uuid references public.lucid_resources(id) on delete set null,catalogue_id uuid references public.catalogues(id) on delete set null,title text,context jsonb not null default '{}'::jsonb,is_private boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.ai_messages (id bigint generated always as identity primary key,conversation_id uuid not null references public.ai_conversations(id) on delete cascade,role text not null,content text not null,context_snapshot jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.learning_events (id bigint generated always as identity primary key,user_id uuid not null references auth.users(id) on delete cascade,catalogue_id uuid references public.catalogues(id) on delete set null,resource_id uuid references public.lucid_resources(id) on delete set null,session_id uuid,event_type text not null,occurred_at timestamptz not null default now(),payload jsonb not null default '{}'::jsonb);
create table if not exists public.notifications (id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,type text not null,title text not null,body text not null,action jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());

create or replace function public.compute_mastery(exposure numeric,understanding numeric,recall numeric,application numeric) returns numeric language sql immutable set search_path=public,pg_temp as $$ select round((coalesce(exposure,0)*.20+coalesce(understanding,0)*.30+coalesce(recall,0)*.25+coalesce(application,0)*.25)::numeric,2) $$;
create or replace function public.level_title(p_level integer) returns text language sql immutable set search_path=public,pg_temp as $$ select case p_level when 1 then 'Curious' when 2 then 'Explorer' when 3 then 'Learner' when 4 then 'Practitioner' when 5 then 'Focused' when 6 then 'Consistent' when 7 then 'Scholar' when 8 then 'Deep Learner' when 9 then 'Mastery Seeker' when 10 then 'Mentor' else 'Mentor' end $$;
create or replace function public.xp_for_action(p_event_type text,p_improvement numeric default 0) returns integer language plpgsql immutable set search_path=public,pg_temp as $$ begin return case p_event_type when 'focus_completed' then 20 when 'chapter_completed' then 30 when 'milestone_completed' then 50 when 'recall_passed' then 20 when 'major_test_completed' then 40 when 'spaced_review_completed' then 20 when 'useful_annotation' then 5 when 'goal_completed' then 100 when 'resource_completed' then 100 when 'room_member_helped' then 10 when 'room_objective_completed' then 50 when 'test_score_improved' then case when p_improvement>0 then 25 else 0 end else 0 end; end $$;

alter table public.notifications enable row level security;
drop policy if exists "lucid notifications own" on public.notifications;
create policy "lucid notifications own" on public.notifications to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
alter table public.badges enable row level security;
drop policy if exists "lucid badges read" on public.badges;
create policy "lucid badges read" on public.badges for select to authenticated using(true);

create or replace function public.track_learning_event(p_event_type text,p_catalogue_id uuid default null,p_resource_id uuid default null,p_session_id uuid default null,p_payload jsonb default '{}'::jsonb) returns public.learning_events language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();r public.learning_events; begin if uid is null then raise exception 'not authenticated'; end if; insert into public.learning_events(user_id,catalogue_id,resource_id,session_id,event_type,payload) values(uid,p_catalogue_id,p_resource_id,p_session_id,p_event_type,coalesce(p_payload,'{}'::jsonb)) returning * into r;return r;end $$;
create or replace function public.apply_xp_event(p_event_type text,p_source_id text default null,p_improvement numeric default 0) returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();amount integer:=public.xp_for_action(p_event_type,p_improvement);total bigint;lvl integer;did_insert boolean;begin if uid is null then raise exception 'not authenticated';end if;insert into public.user_xp(user_id) values(uid) on conflict do nothing;if amount>0 then insert into public.xp_ledger(user_id,event_type,amount,source_id) values(uid,p_event_type,amount,p_source_id) on conflict (user_id,event_type,(coalesce(source_id,''))) do nothing;did_insert:=found;if did_insert then update public.user_xp set xp=xp+amount,updated_at=now() where user_id=uid;else amount:=0;end if;end if;select xp into total from public.user_xp where user_id=uid;lvl:=greatest(1,floor(sqrt(greatest(total,0)::numeric/50.0))::int+1);update public.user_xp set level=lvl where user_id=uid;insert into public.user_levels(user_id,level,title) values(uid,lvl,public.level_title(lvl)) on conflict do nothing;return jsonb_build_object('xp_awarded',amount,'total_xp',total,'level',lvl,'title',public.level_title(lvl));end $$;
create or replace function public.update_concept_mastery(p_concept_id uuid,p_exposure numeric default null,p_understanding numeric default null,p_recall numeric default null,p_application numeric default null,p_evidence jsonb default '{}'::jsonb) returns public.concept_mastery language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();r public.concept_mastery;begin if uid is null then raise exception 'not authenticated';end if;insert into public.concept_mastery(user_id,concept_id,exposure,understanding,recall,application,mastery,evidence) values(uid,p_concept_id,coalesce(p_exposure,0),coalesce(p_understanding,0),coalesce(p_recall,0),coalesce(p_application,0),public.compute_mastery(coalesce(p_exposure,0),coalesce(p_understanding,0),coalesce(p_recall,0),coalesce(p_application,0)),coalesce(p_evidence,'{}'::jsonb)) on conflict(user_id,concept_id) do update set exposure=coalesce(p_exposure,public.concept_mastery.exposure),understanding=coalesce(p_understanding,public.concept_mastery.understanding),recall=coalesce(p_recall,public.concept_mastery.recall),application=coalesce(p_application,public.concept_mastery.application),mastery=public.compute_mastery(coalesce(p_exposure,public.concept_mastery.exposure),coalesce(p_understanding,public.concept_mastery.understanding),coalesce(p_recall,public.concept_mastery.recall),coalesce(p_application,public.concept_mastery.application)),evidence=coalesce(p_evidence,public.concept_mastery.evidence),updated_at=now() returning * into r;return r;end $$;

revoke all on function public.apply_xp_event(text,text,numeric) from public,anon,authenticated;
revoke all on function public.track_learning_event(text,uuid,uuid,uuid,jsonb) from public,anon,authenticated;
revoke all on function public.update_concept_mastery(uuid,numeric,numeric,numeric,numeric,jsonb) from public,anon,authenticated;
grant execute on function public.apply_xp_event(text,text,numeric) to authenticated;
grant execute on function public.track_learning_event(text,uuid,uuid,uuid,jsonb) to authenticated;
grant execute on function public.update_concept_mastery(uuid,numeric,numeric,numeric,numeric,jsonb) to authenticated;

create unique index if not exists ux_lucid_xp_source on public.xp_ledger(user_id,event_type,coalesce(source_id,''));
create index if not exists idx_lucid_notifications_user_time on public.notifications(user_id,created_at desc);
create index if not exists idx_lucid_events_user_time on public.learning_events(user_id,occurred_at desc);
create index if not exists idx_lucid_events_resource_time on public.learning_events(resource_id,occurred_at desc);
create index if not exists idx_lucid_mastery_user on public.concept_mastery(user_id,mastery asc);
create index if not exists idx_lucid_room_events_time on public.room_events(room_id,occurred_at desc);

insert into public.badges(slug,name,family,description,rule) values
('streak-7','7 Day Consistency','consistency','Participate across seven days.','{"days":7}'),
('streak-30','30 Day Consistency','consistency','Participate across thirty days.','{"days":30}'),
('streak-100','100 Day Consistency','consistency','Participate across one hundred days.','{"days":100}'),
('pages-100','100 Pages','reading','Reach one hundred pages.','{"pages":100}'),
('pages-1000','1,000 Pages','reading','Reach one thousand pages.','{"pages":1000}'),
('deep-10','10 Focus Sessions','deep_work','Complete ten focused sessions.','{"sessions":10}'),
('deep-50','50 Focus Sessions','deep_work','Complete fifty focused sessions.','{"sessions":50}'),
('practice-50','50 Questions','practice','Complete fifty practice questions.','{"questions":50}'),
('practice-250','250 Questions','practice','Complete two hundred and fifty practice questions.','{"questions":250}'),
('room-10','10 Room Contributions','collaboration','Make ten useful room contributions.','{"contributions":10}'),
('room-50','50 Room Contributions','collaboration','Make fifty useful room contributions.','{"contributions":50}'),
('resource-1','First Resource Complete','completion','Complete your first learning resource.','{"resources":1}'),
('resource-5','Five Resources Complete','completion','Complete five learning resources.','{"resources":5}')
on conflict(slug) do nothing;
